<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bot">

    <!-- constants -->
    <xacro:property name="PI" value="3.141592653589793" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_depth" value="0.2" />
    <xacro:property name="base_height" value="0.1" />

    <xacro:property name="x_offset" value="0.1" />
    <xacro:property name="wheel_width" value="0.05" />
    <xacro:property name="wheel_gap" value="0.005" />

    <!-- macros -->
    <xacro:macro name="box_inertial" params="mass x y z">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="${1/12*mass*(y*y+z*z)}" ixy="0.0" ixz="0.0" iyy="${1/12*mass*(x*x+z*z)}" iyz="0.0" izz="${1/12*mass*(y*y+x*x)}" />
        </inertial>
    </xacro:macro>

    <!-- define colors -->
    <material name="blue">
        <color rgba="0 0 0.8 1" />
    </material>
    <material name="black">
        <color rgba="0 0 0 1" />
    </material>
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>
    <material name="purple">
        <color rgba="0.3098 0.1765 0.4980 1" />
    </material>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_width} ${base_depth} ${base_height}" />
            </geometry>
            <material name="white" />
        </visual>

        <collision>
            <geometry>
                <box size="${base_width} ${base_depth} ${base_height}" />
            </geometry>
        </collision>


    </link>
    <gazebo reference="base_link">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="base_link-base_footprint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 -0.15" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint" />

    <joint name="base_link-base_inertial" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0" />
        <parent link="base_link" />
        <child link="base_inertial" />
    </joint>

    <!-- Inertial link stores the robot's inertial information -->
    <link name="base_inertial">
        <xacro:box_inertial mass="1" x="${base_width}" y="${base_depth}" z="${base_height}" />
    </link>

    <joint name="base_to_left_wheel" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin rpy="${PI/2} 0 0" xyz="${x_offset} ${base_depth/2+wheel_gap+wheel_width/2} 0" />
        <axis rpy="0 0 0" xyz="0 0 1" />
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="0.05" radius="0.1" />
            </geometry>
            <material name="black" />
        </visual>

        <collision>
            <geometry>
                <cylinder length="0.05" radius="0.1" />
            </geometry>
        </collision>

        <inertial>
            <mass value="0.1" />
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
        </inertial>
    </link>
    <gazebo reference="left_wheel">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="base_to_right_wheel" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin rpy="${PI/2} 0 0" xyz="${x_offset} ${-(base_depth/2+wheel_gap+wheel_width/2)} 0" />
        <!-- <origin rpy="1.5707963267948966 0 0" xyz="0.1 -0.13 0" /> -->
        <axis rpy="0 0 0" xyz="0 0 1" />
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="0.05" radius="0.1" />
            </geometry>
            <material name="black" />
        </visual>

        <collision>
            <geometry>
                <cylinder length="0.05" radius="0.1" />
            </geometry>
        </collision>

        <inertial>
            <mass value="0.1" />
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
        </inertial>
    </link>
    <gazebo reference="right_wheel">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="base_to_caster" type="revolute">
        <parent link="base_link" />
        <child link="caster" />
        <origin xyz="-0.15 0 -0.05" />
        <limit lower="0" upper="0" effort="0" velocity="0" />
        <axis rpy="0 0 0" xyz="0 0 1" />
    </joint>

    <link name="caster">
        <visual>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
            <material name="purple" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="0.05" />
            </geometry>
        </collision>

        <inertial>
            <mass value="0.2" />
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
        </inertial>
    </link>
    <gazebo reference="caster">
        <mu1>0.0</mu1>
        <mu2>0.0</mu2>
        <material>Gazebo/Purple</material>
    </gazebo>

    <!-- differential_drive_controller plugin -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <!-- <ros>
                <namespace>/bot</namespace>
                <argument>cmd_vel:=cmd_demo</argument>
                <argument>odom:=odom_demo</argument>
            </ros> -->
            <update_rate>100</update_rate>
            <left_joint>base_to_left_wheel</left_joint>
            <right_joint>base_to_right_wheel</right_joint>
            <wheel_separation>0.26</wheel_separation>
            <wheel_diameter>0.2</wheel_diameter>
            <odometry_frame>odom</odometry_frame>
            <max_wheel_torque>20</max_wheel_torque>
            <!-- Wheel acceleration, in rad/s^2, defaults to 0.0 rad/s^2 -->
            <max_acceleration>1.0</max_acceleration>
        </plugin>
    </gazebo>
</robot>